# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-31 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ico',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
