# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-01 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_feedback_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Rating'),
        ),
    ]
