# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-04 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20170201_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Rating'),
        ),
    ]
