# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-04 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_question_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='theme',
            field=models.CharField(default='x2', max_length=80),
        ),
    ]
