# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-05 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20170205_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Feedback')),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Vendor'),
        ),
    ]
